ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Install Miniconda and create the 'comfystream' environment
ARG PYTHON_VERSION=3.10
ENV CONDA_DIR /workspace/miniconda3
ENV PATH $CONDA_DIR/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends wget curl ca-certificates && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh && \
    conda init bash && \
    conda config --set auto_activate_base false && \
    conda clean -a -y && \
    conda create -n comfystream python=$PYTHON_VERSION -y && \
    conda run -n comfystream pip install --no-cache-dir --upgrade pip==23.3.2 setuptools==69.5.1 wheel==0.43.0 && \
    conda clean -a -y && \
    apt-get purge -y --auto-remove wget curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PIP_PREFER_BINARY=1

# Install StreamDiffusion dependencies into the comfystream environment
RUN conda run -n comfystream pip install --no-cache-dir \
    torch==2.1.0 \
    torchvision==0.16.0 \
    xformers===0.0.22.post7 \
    --index-url https://download.pytorch.org/whl/cu121

# Install StreamDiffusion @ b623251 (latest at time of writing) into the comfystream environment
RUN conda run -n comfystream pip install git+https://github.com/cumulo-autumn/StreamDiffusion.git@b623251#egg=streamdiffusion[tensorrt]

# Install TensorRT extension and ensure compatible dependencies into the comfystream environment
RUN conda run -n comfystream pip install --no-cache-dir --force-reinstall \
    huggingface-hub==0.25.2 \
    transformers==4.38.2
RUN conda run -n comfystream python -m streamdiffusion.tools.install-tensorrt

WORKDIR /app

# Create symlink for where StreamDiffusion builds TensorRT engines at runtime
RUN ln -s /models/StreamDiffusion--engines ./engines
